name: CI Pipeline

on:
  push:
    branches: [main]  # Запускать только при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем GitHub-hosted runner с Ubuntu

    steps:
      - uses: actions/checkout@v4  # Клонирует код из репозитория

      - name: Встановлення pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Встановлення Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Як локально (Node 24)
          cache: pnpm # Кешує залежності між запусками

      - name: Встановлення залежностей
        run: pnpm install --frozen-lockfile

      - name: Линтинг
        run: pnpm run lint

      - name: Запуск тестов
        run: pnpm run test

        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}